### ISSUE TITLE
Declaration and usages

### ISSUE THREAD

**Issue by zored** [adelf/idea-php-dotenv-plugin#1]
It would be great if we could find usages from `.env` file and find declaration from `getenv('SOME_ARGUMENT')` argument. Just like how we find usages and declarations of methods.

The example is in Symfony plugin: there you can move from service name to class and backwards.

Thank you for great plugin anyway 👍

**Comment by adelf** [comment]
Thanks. I was thinking about it, but to implement Go to declaration I have to teach PhpStorm to work with .env files. Create syntax lexer and grammar. It'll take some time, but I'll try to do it.

**Comment by Haehnchen** [comment]
Lexer would be fine. but what is about using `FilenameIndex.getFilesByName(project, ".env")` to get all files instead of indexing them?

**Comment by adelf** [comment]
@Haehnchen I'm not sure. In each autocomplete request, read and analyze file contents... Anyway, I wrote it not only for laravel, but for another project, where dotenv library was used directly. And for this library .env file can be everywhere. not only on project root.

**Comment by adelf** [comment]
I implemented this but it doesn't work in PhpStorm. It has a little bug with uncorrect file type calculating for file with empty names, like '.env'. In the same time IDEA Ultimate works as expected. 
https://youtrack.jetbrains.com/issue/WI-36033 - if you want to vote ;-)

**Comment by adelf** [comment]
implemented in 0.2
