### ISSUE TITLE
Plugin doesn't work with EAP 2022.1

### ISSUE THREAD

**Issue by bigjoky** [adelf/idea-php-dotenv-plugin#102]
Good evening,

I looked for this issue but is not registered yet.

I'm working with the WebStorm EAP 2022.1 version and the plugin is not recognised, requires the IDE build 213 as this image below.

<img width="409" alt="Captura de pantalla 2022-01-29 a las 17 37 51" src="https://user-images.githubusercontent.com/4026060/151669213-646fea3f-1751-4e60-8028-f241e757ce13.png">

**Comment by adelf** [comment]
The update waits for approval from JetBrains. But you can download it here - https://plugins.jetbrains.com/plugin/9525--env-files-support/versions/stable/155499
Don't close this issue for some time. Let other people read this.

**Comment by bigjoky** [comment]
Great news! thank you so much!

I'll keep it open for a while, anyway I think that you can close it when you consider 😉

**Comment by sakhdevel** [comment]
Sorry, I'm not sure if I should create another issue. Can you explain please.
I have PhpStorm 2021.3.2. The plugin is installed through the settings as usual. But it doesn't highlight anything in .env files (doesn't work?).
Here https://plugins.jetbrains.com/plugin/9525--env-files-support it says that the plugin is compatible with the version of my IDE. I've tried manual installation. The result is the same.

**Comment by adelf** [comment]
@sakhdevel please check - https://github.com/adelf/idea-php-dotenv-plugin/issues/90#issuecomment-898388301
