### ISSUE TITLE
Observation: Only works with one .env file

### ISSUE THREAD

**Issue by SadSack963** [adelf/idea-php-dotenv-plugin#103]
Using PyCharm 2021.3.2 (Community Edition) on Windows 10.

I have three .env files in the root project folder (for test purposes):
.env
.env.local
.env.development

In main.py I get the pop-up for suggestions with the .env file, and I can navigate to the declarations (Ctrl+B).

I do not get the suggestion pop-up for .env.local or .env.development, but I can navigate to the declarations once the code is typed in.

If I rename .env and .env.development, then I do get the suggestions pop-up for .env.local. 

Similarly,  if I rename .env and .env.local, then I do get the suggestions pop-up for .env.development.

Is this behaviour expected?

Feature Request: Would it be possible to use an external .env file with this plugin, i.e. outside of the project folder?

**Comment by adelf** [comment]
Fixed. Thanks. I'll try to release a new version soon.

**Comment by SadSack963** [comment]
Wow. That's a rapid response. Thank you.
