### ISSUE TITLE
Value Preview is displayed

### ISSUE THREAD

**Issue by nixoncode** [adelf/idea-php-dotenv-plugin#104]
Thanks for such a great plugin.

I just want to bring to attention what it means to show previews of `key` and `value` from the  **.env** file.

Values of .env are secrets, so let's keep it that way. Think of it as HTML's password input.

I think it would be nice if we just show the key, and Hide the value

**Comment by adelf** [comment]
Hi.

Please check Preferences | Languages & Frameworks | DotEnv

**Comment by nixoncode** [comment]
Thanks for pointing me to that.

Really helpful.
