### ISSUE TITLE
WSL2 error : export: ProgramFiles(x86): bad variable name

### ISSUE THREAD

**Issue by aanno** [adelf/idea-php-dotenv-plugin#105]
With IntelliJ on windows, the plugin seems to cause problems with WSL support. See https://stackoverflow.com/questions/69721714/intelij-idea-in-wsl2-error-export-programfilesx86-bad-variable-name for details.

I encountered the problem as well and could confirm that the problem is still present in IntelliJ IDEA 2022.1.2 (Ultimate Edition).

**Comment by adelf** [comment]
I think it's the EnvFile plugin issue. Not this one. .env files support only provides syntax support and some completions.
