### ISSUE TITLE
Plugin doesn't work with the latest build of PyCharm 2022.2

### ISSUE THREAD

**Issue by createNull** [adelf/idea-php-dotenv-plugin#107]
Just updated to PyCharm 2022.2 build #PC-222.3345.131.
Worked on previous build

**Comment by adelf** [comment]
What plugin version do you use?
There is 2022.2 version for 2022.2 IDEs.

**Comment by createNull** [comment]
> What plugin version do you use? There is 2022.2 version for 2022.2 IDEs.

Latest version. Related to this [issue](https://github.com/ashald/EnvFile/issues/186)

**Comment by adelf** [comment]
.env files support and EnvFile - are totally different and independent plugins.

**Comment by createNull** [comment]
I know that, but ok.
