### ISSUE TITLE
Plugin doesn't work with EAP 2022.3

### ISSUE THREAD

**Issue by mirelon** [adelf/idea-php-dotenv-plugin#108]
![image](https://user-images.githubusercontent.com/1101497/191904321-4ab6a707-9f9e-414f-b5fc-5f68e2d0fd49.png)

**Comment by adelf** [comment]
The new release will be approved soon.

You can download and install it manually from here:
https://plugins.jetbrains.com/plugin/9525--env-files-support/versions/stable/228993
