### ISSUE TITLE
Completion support for python os.getenv()

### ISSUE THREAD

**Issue by ex-nerd** [adelf/idea-php-dotenv-plugin#11]
`os.getenv('VAR_NAME')` is one of several ways to get at environment variables in python, but does not seem to be supported in the same way that `os.environ.get('VAR_NAME')` and others are.

**Comment by adelf** [comment]
Is there other standard ways? Just to implement all of thems...

**Comment by ex-nerd** [comment]
There are a bunch of different ways in python to interact with the `os.environ` dictionary (just like any dictionary), but `os.getenv()` is the only other way I know of.  This has as good a breakdown as anything else: https://stackoverflow.com/questions/4906977/access-environment-variables-from-python

**Comment by adelf** [comment]
implemented in 0.6
