### ISSUE TITLE
Doesn't work in .env, but works in .env.example (phpstorm)

### ISSUE THREAD

**Issue by sarik-k** [adelf/idea-php-dotenv-plugin#111]
I'm using this plugin in PhpStorm on Windows. 

Syntax highlighting, commenting, etc does not work in .env file. But it works perfectly file in .env.example file.

**Comment by adelf** [comment]
Hello. Please check - https://github.com/adelf/idea-php-dotenv-plugin/issues/90#issuecomment-898388301

**Comment by sarik-k** [comment]
Thanks!
