### ISSUE TITLE
Unable To Use "HasFactories" with Factories Under Subfolders

### ISSUE THREAD

**Issue by megahash** [adelf/idea-php-dotenv-plugin#112]
When adding "HasFactory" to a model, where the factory is in the root folder (database/factories), no issues are raised by PhpStorm. However, if you have a factory that is in a subfolder, let's say (database/factories/test), an alert is raised (Can't find the factory class).

When I disable the plugin, I don't receive the error notification. I have a paid subscription to your plugin.
![Issue with HasFactory](https://user-images.githubusercontent.com/106414068/214213135-befb617b-b895-4bdd-a301-8d6b980f6659.png)

**Comment by adelf** [comment]
Hi. Seems, you've chosen wrong repository to create issue)

Anyway, does this work in Laravel? Without `$model = Role::class;` in the factory class?

**Comment by adelf** [comment]
Also, if you have another factory fetching strategy in your app you can press Alt-Enter and Disable it for the whole project.

<img alt="image" src="https://user-images.githubusercontent.com/2818394/214225490-b453785a-5953-4681-adb1-e1f50d0c1ad4.png">

**Comment by megahash** [comment]
@adelf Thank you for the help. I added $model = Role::class; and the highlighted issue went away. I love the plugin!
