### ISSUE TITLE
Go to Definition doesn't work in IntelliJ IDEA 2022.3.3

### ISSUE THREAD

**Issue by rapman** [adelf/idea-php-dotenv-plugin#115]
Don't work,,, I see color markup but Go to Definition doesn't work

**Comment by adelf** [comment]
Hello.

Where it doesn't work? From which call?

**Comment by drMonro** [comment]
Like I use "Go to" with other definitions in project  - just put mouse cursor with pressed "Ctrl" on def in my .env file and click it - and nothing is going on now
There is the same then I try to "Go to" from files there i'm using data from .env file 

[Screen](https://prnt.sc/zYwRIdPkcGoQ)

**Comment by adelf** [comment]
Is it javascript calls? JavaScript plugin has its own completion for .env values.

**Comment by drMonro** [comment]
oh.. this plugin work only in php?

**Comment by adelf** [comment]
PHP, Ruby, Python, Go, Java, Kotlin. It supported Js in the past, but JetBrains implemented their own support for .env files, so I removed it.
