### ISSUE TITLE
Not compatible with Php Storm 2023.2 EAP

### ISSUE THREAD

**Issue by rhorbas** [adelf/idea-php-dotenv-plugin#116]
![grafik](https://github.com/adelf/idea-php-dotenv-plugin/assets/4625205/b5683072-71e8-43d8-98ae-ffa4b36b8dd2)
![grafik](https://github.com/adelf/idea-php-dotenv-plugin/assets/4625205/25e7d5b6-8e88-45a7-a454-9f8e995ced8b)

**Comment by ofry** [comment]
Could it be closed now? .​env files support version 2023.2 compatible with PHPStorm  2023.2 — 2023.2.6.

Released on May 24, 2023
