### ISSUE TITLE
extremely slow

### ISSUE THREAD

**Issue by luxferre** [adelf/idea-php-dotenv-plugin#123]
choppy changes view / project tree scrolling rendering, 1 FPS

**Comment by adelf** [comment]
Hello. How is this connected with .env plugin?

**Comment by luxferre** [comment]
hi! i'm sorry! i believe this was misclick

ср, 7 февр. 2024 г., 20:25 Adel ***@***.***>:

**Comment by adelf** [comment]
ok. no problem)
