### ISSUE TITLE
[FEATURE] Add Cloaking functionality

### ISSUE THREAD

**Issue by badmike** [adelf/idea-php-dotenv-plugin#125]
I'd like to propose a functionality to cloak the values of the env file, when shown on screen. It should aim to enhance security during presentations, live streams on platforms like Twitch or YouTube, and screencasts by hiding (and showing) the sensitive information present in the environment file(s).

There should be a command that can be triggered to toggle between showing the sensitive information or hiding it. There's a similar feature realised for Visual Studio Code through the plugin https://github.com/johnpapa/vscode-cloak.

**Comment by adelf** [comment]
Please check the 2024.1 version. Turn on this option and reopen .env files

<img width="721" alt="image" src="https://github.com/adelf/idea-php-dotenv-plugin/assets/2818394/f5a7b4c5-8f4f-431f-b43f-2d4dea362b0c">

**Comment by badmike** [comment]
Awesome – Thank you very much. Works like a charm!
