### ISSUE TITLE
Plugin 'One Dark Theme' is not compatible with WS-242.10180.31

### ISSUE THREAD

**Issue by solidados** [adelf/idea-php-dotenv-plugin#129]
- [x] Plugin 'One Dark Theme' (version '5.10.0') is not compatible with the current version of the IDE, because it requires build 241.* or older but the current build is WS-242.10180.31

Please release plugin versions that are compatible with 2024.2

**Comment by adelf** [comment]
Use this plugin's bug tracker ;-)
