### ISSUE TITLE
GoLand support

### ISSUE THREAD

**Issue by adelf** [adelf/idea-php-dotenv-plugin#13]
https://github.com/joho/godotenv

**Comment by dlsniper** [comment]
Hi,

I would love to help improve the plugin by adding support for GoLand but I'm not sure how to compile it locally.

I get a lot of errors like:

```
Error:(5, 30) java: package com.jetbrains.php.lang does not exist

[...]

Error:(26, 41) java: cannot find symbol
  symbol:   class FunctionReference
  location: class ru.adelf.idea.dotenv.util.PsiUtil
```

How can I setup the plugin so that I can work on it?
Thank you!

**Comment by adelf** [comment]
Hi, @dlsniper .
Thank you for trying to help. 
Actually, this plugin... became monolithic. It has support for PHP, Ruby, Python IDE's and building it not very simple. We have to create Plugin SDK with all jar's for php, ruby, python langs. And I also going to add plugins for go and js :) Much better was to create different plugins. For each IDE... But it's really inconvenient for using and supporting too... 
I'll try to implement all planned features tomorrow. And release 0.6. I think go and js shouldn't be a problem. And also I'll try to describe how to build this plugin in somewhere.

**Comment by dlsniper** [comment]
Cool. I can definitely handle the Go stuff, when 0.6 comes out then. Thank you for your work on the plugin!

**Comment by Haehnchen** [comment]
@adelf you should switch to _optional_ dependencies in _plugin.xml_

**Comment by adelf** [comment]
They are all optional :)

**Comment by Haehnchen** [comment]
oh, i see sweet :)

**Comment by adelf** [comment]
I met some uncommon problem by implementing this. Maybe I misunderstood something, but IntelliJ's Go implementation looks strange and has another package prefix. com.goide. So, maybe there is something interesting, I dunno. I hope I'll manage to implement it. but only in 0.7. Sorry.

**Comment by dlsniper** [comment]
I'm happy to help if needed or ping the developers if you need any resources, please let me know if there's anything that I can.

**Comment by adelf** [comment]
@dlsniper I just don't know why it happens...
I add /plugins/intellij-go-plugin/lib/intellij-go-plugin.jar as a dependency, try to run this plugin and get errors like "java.lang.NoClassDefFoundError: com/goide/GoFileType". I think I just doing some very simple thing wrong :)

**Comment by dlsniper** [comment]
Hi @adelf, thanks for pinging me on this. Please let me ping @zolotov on this issue as he's familiar with the Go IDE.

**Comment by zolotov** [comment]
@adelf adding some jar to classpath is needed only for compilation. To install a plugin in the IDE, you need to install it in config directory, e.g. via regular `File | Settings | Plugins`.

**Comment by zolotov** [comment]
Here is the example on how to configure development for PhpStorm: http://www.jetbrains.org/intellij/sdk/docs/phpstorm/setting_up_environment.html. The same is applied for Go.

**Comment by adelf** [comment]
@zolotov thanks for helping. I have this error when I trying to run or debug plugin. Also when I install it from File | Settings | Plugins.  I didn't have anything like this with Js, PHP, python and ruby... 
I think it's something very simple which I haven't set up well...

**Comment by zolotov** [comment]
> Also when I install it from File | Settings | Plugins.

Take a look at the logs then and see whether Go plugin was even loaded.

**Comment by dlsniper** [comment]
I've tried this as well and either repeated the same mistake as @adelf or there's something else that neither of us could figure out.
Source: https://github.com/dlsniper/idea-php-dotenv-plugin/tree/go-support (@adelf's go-support branch rebased on latest master).
IDE Logs: https://gist.github.com/dlsniper/665d7be7131537eab3d548e057d5d3b3

![2018-02-28 3](https://user-images.githubusercontent.com/607868/36818928-226c6652-1cdf-11e8-949c-149d5f0f5548.png)

![2018-02-28 4](https://user-images.githubusercontent.com/607868/36818933-26097bd8-1cdf-11e8-9047-7562c71c565e.png)

Please let me know if I should open this on YouTrack instead.

**Comment by zolotov** [comment]
@dlsniper it means the plugin is not installed in internal IDE, so install it. To avoid exceptions it should be optional dependency, so the go-part won't be loaded until Go plugin will be installed

**Comment by dlsniper** [comment]
@zolotov it is installed, see the logs https://gist.github.com/dlsniper/665d7be7131537eab3d548e057d5d3b3#file-idea-log-L16

**Comment by adelf** [comment]
@zolotov maybe the problem is that Go plugin is custom too and the order is wrong? I hadn't any problems with other IDE's.
Dependency is optional.
https://github.com/adelf/idea-php-dotenv-plugin/blob/go-support/resources/META-INF/plugin.xml#L41

**Comment by zolotov** [comment]
@adelf go-capable is the wrong dependency, you should depend on Go plugin, not on IDE that can install Go plugin.
