### ISSUE TITLE
Doesnt work with PhpStorm 2024.2.3

### ISSUE THREAD

**Issue by unlike777** [adelf/idea-php-dotenv-plugin#138]
Error on Plugins page:

`Incompatible: requires IDE build 212.* or earlier`

**Comment by adelf** [comment]
Please download a new update.

**Comment by aowie1** [comment]
I'm having the same issue. I don't see a new update...

**Comment by adelf** [comment]
https://plugins.jetbrains.com/plugin/9525--env-files-support/versions/stable/589325?noRedirect=true

Compatibility:
> PhpStorm — 2023.2 — 2024.2.4

**Comment by unlike777** [comment]
@adelf thx!
Is it possible to manually update the plugin?

**Comment by adelf** [comment]
Yes. You can download and install the file. But your IDE should update automatically.
