### ISSUE TITLE
Completion does not work in Intellij IDEA in React with TypeScript

### ISSUE THREAD

**Issue by gitowiec** [adelf/idea-php-dotenv-plugin#18]
I have a React project in TypeScript and the plugin does not allow of completion in `.env` of used environment variables as:
### config.js:
```
const APP_URL = process.env.APP_URL || 'http://127.0.0.1:8899';
```
Go to first usage place works (I CTRL+click it and IDE gets me to the specific file where puts cursor at `process.env.APP_URL`)

**Comment by adelf** [comment]
I added typescript support in 0.7. Hope it will help.
