### ISSUE TITLE
Syntax highlighting - Feature Request

### ISSUE THREAD

**Issue by blackfyre** [adelf/idea-php-dotenv-plugin#2]
Hi!

I don't really know (and won't pretend to), how PHPStorm and the other IDEA offspring do this, but some kind of highlighting for the `.env` files would be helpful :)

**Comment by kAlvaro** [comment]
Until I discovered this plug-in I was using Bash highlighter (not sure whether it's builtin or third-party) and it worked fine (save for the insistence of adding a shebang). Perhaps it could be taken as starting point.

**Comment by alex-holt** [comment]
Yes please!

This will be a real help as our company .env files are LONG and difficult to navigate

**Comment by luiz-brandao** [comment]
You can get syntax highlighting by setting .env as an _ini_ type type. Go to Settings > Editor > File Types, then under _Recognized File Types_ select __Ini__ and then add .env to the _Registered Patterns_ list.

**Comment by YassineGherbi** [comment]
@luiz-brandao-jr the only problem with that is that you'll lose all the functionality the plugin has to offer... :(

**Comment by adelf** [comment]
Finally, did it :)
in 0.7
