### ISSUE TITLE
hope can support for run config

### ISSUE THREAD

**Issue by bluelovers** [adelf/idea-php-dotenv-plugin#21]
hope can support for run config

**Comment by dlsniper** [comment]
You can see follow the code here https://github.com/Ashald/EnvFile/tree/develop/project/products to see how to support such a feature.

**Comment by adelf** [comment]
@dlsniper I don't know... Should I implement it in this plugin?
It becomes like a God object :)
Or maybe it's ok...

**Comment by dlsniper** [comment]
I think it would be great to have it.
Here's an example of people needing this feature and why https://youtrack.jetbrains.com/issue/GO-5420#focus=streamItem-27-3050372-0-0
What do you think?

**Comment by adelf** [comment]
Ok. I'll try :)

**Comment by dlsniper** [comment]
Thank you!

**Comment by adelf** [comment]
Seems, this plugin(https://github.com/ashald/EnvFile) implemented some integrations(with GoLand). And I don't think my plugin should do the same... and also, Single Responsibility Principle :)
