### ISSUE TITLE
Syntax Highlighting in Php Storm

### ISSUE THREAD

**Issue by msthzn** [adelf/idea-php-dotenv-plugin#23]
Hello, first of all thx for plugin. Would you please add syntax highlighting in phpstorm. PhpStorm is one of the most popular u know, without syntax highlighting plugin is nothing in phpstorm :(

**Comment by jezmck** [comment]
At the very least, a different colour for comments would be amazing.

**Comment by jezmck** [comment]
This is a duplicate of #2.
