### ISSUE TITLE
request: add "all" versioned file into .gitignore as exclude

### ISSUE THREAD

**Issue by bluelovers** [adelf/idea-php-dotenv-plugin#24]
hope can have a option action for this
for some Special usage

when we have 

.gitignore
```
*.js
```

files
```
aaa.js (in git)
bbb.js (not in git)
```

after this action

.gitignore has

```
*.js
!aaa.js
```

**Comment by jezmck** [comment]
I think you may have raised this issue on the wrong repo.

**Comment by bluelovers** [comment]
oops looks like i  open wrong window
