### ISSUE TITLE
Prevent parsing of .env.js

### ISSUE THREAD

**Issue by gorbunov** [adelf/idea-php-dotenv-plugin#27]
.env.js (.env.example.js, etc) files are parsed and colored by plugin instead of javascript.

![2018-09-03 9 16 48](https://user-images.githubusercontent.com/198664/44965937-2b1c6a00-af5a-11e8-88ee-1f0dca2c7553.png)

**Comment by adelf** [comment]
Is it a usual names for javascript files?
Why are they prefixed by dot? some library? standard?
