### ISSUE TITLE
custom file name like .env-default

### ISSUE THREAD

**Issue by liesislukas** [adelf/idea-php-dotenv-plugin#31]
I know this is not a standard name of env file but the project I work on uses such. Any way to get highlighting for custom env file?

it works great for `.env` file but no highlight for `.env-default`.

**Comment by adelf** [comment]
You can configure it here(Settings > Editor > File types):
![](http://adelf.ru/files/dotenv_type.png)

**Comment by liesislukas** [comment]
exactly what I was looking for :)
