### ISSUE TITLE
Notify when .env files aren't associated with plugin

### ISSUE THREAD

**Issue by adelf** [adelf/idea-php-dotenv-plugin#35]
https://github.com/Haehnchen/idea-php-laravel-plugin/commit/faa4be504b697e78577698f4bfe97daf9238aa79

https://www.programcreek.com/java-api-examples/?api=com.intellij.openapi.fileTypes.LanguageFileType

**Comment by ktomk** [comment]
If this has not been implemented, I can report that my EAP of Phpstorm 2019.2 did notify me about this plugin already. So this is perhaps not necessary to implement at all as the IntelliJ platform already has it.

**Comment by adelf** [comment]
Thanks, @ktomk . I've created this issue when I was working with 2018 versions.
