### ISSUE TITLE
CLion support

### ISSUE THREAD

**Issue by eugenesaenko** [adelf/idea-php-dotenv-plugin#37]
Could you please add support for CLion IDE?

**Comment by adelf** [comment]
Hi, @eugenesaenko . What support do you mean? Only .env files highlighting or... is there any packages which inject environment variables from .env?

**Comment by eugenesaenko** [comment]
.env file syntax highlighting with autocompletion in docker-compose files, etc.

**Comment by adelf** [comment]
Auto-completion in C/C++ code? If yes, which functions and classes fetching environment variables there?

**Comment by eugenesaenko** [comment]
No, i dont need autocompletion in C. Only syntax highlight in .env.* files

**Comment by adelf** [comment]
I allowed to use this plugin in every IDE :)
