### ISSUE TITLE
Multi-line strings

### ISSUE THREAD

**Issue by demalexx** [adelf/idea-php-dotenv-plugin#41]
Is it planned to add support of multi-line strings? I'm not sure how it could be done, but sometimes I miss this feature :) Thanks.

**Comment by adelf** [comment]
You mean alternative syntax from here - https://github.com/bkeepers/dotenv#multi-line-values ?

**Comment by demalexx** [comment]
Kind of.

**Comment by adelf** [comment]
Do you have any other standards of that? Pleaseshare. This plugin supports a lot of languages :)

**Comment by demalexx** [comment]
I don't know the best way of implementing this :) I use direnv and looks like multi-line strings could be written like `VAR=$'line1\nline2'`.
With proper .envrc it will be translated into `export VAR=$'line1\nline2'`.

**Comment by adelf** [comment]
![image](https://user-images.githubusercontent.com/2818394/62543573-d159a980-b866-11e9-9622-a828e8e9a13b.png)
As you see, plugin supports variables like `VAR=$'line1\nline2'`. The problem is only with real multiline variables :) I can try to solve it

**Comment by adelf** [comment]
Included to 2020.1 release.
