### ISSUE TITLE
Downgrade to 0.7 on update to EAP1 2019.3 WebStorm

### ISSUE THREAD

**Issue by Alexsey** [adelf/idea-php-dotenv-plugin#45]
After I have reinstalled WebStorm 2019.2.3 with EAP1 2019.3 the IDE has prompts with plugin update with downgrade proposal from 0.8 to 0.7
![pluginUpdate](https://user-images.githubusercontent.com/6392013/64909772-f6202700-d718-11e9-9932-bb14148a6f65.png)
I have downgraded that plugin. The uninstall it, and now in plugin repo I see 0.7 version, but with Jul 29, 2019 date, just like the date near 0.8 version in [JetBrains plugins repo](https://plugins.jetbrains.com/plugin/9525--env-files-support)
![versionAndDate](https://user-images.githubusercontent.com/6392013/64909740-ba855d00-d718-11e9-9597-4a181d5c6d74.png)

**Comment by adelf** [comment]
Hi. Yes, IntelliJ started to ask 'until' version and I put 2019.2 there.
I'll release 2019.3 version next week. Thanks.

**Comment by adelf** [comment]
2019.3 version is available.
