### ISSUE TITLE
.env variables not being recognized

### ISSUE THREAD

**Issue by lfbn** [adelf/idea-php-dotenv-plugin#46]
Hi,

I have this plugin installed in PhpStorm 2019.2.3 but the .env variables present on my .env file are not being recognized.

![image](https://user-images.githubusercontent.com/6152567/67673551-3c9cae80-f972-11e9-9316-af4a452ed792.png)

Anyone can help me out debugging this?

**Comment by adelf** [comment]
Environment variables in PHP should be fetched with functions like getenv
https://www.php.net/manual/en/function.getenv.php
-- 
Adel Fayzrakhmanov.
