### ISSUE TITLE
Dockerfile string highlight

### ISSUE THREAD

**Issue by Catastropha** [adelf/idea-php-dotenv-plugin#48]
In Dockerfile, after a string is declared everything else is highlighted as string.

![dockerfile](https://user-images.githubusercontent.com/1425601/71707874-03a30f00-2de5-11ea-9c26-a166d5ebb2b9.png)

**Comment by adelf** [comment]
Hi, @Catastropha .
This plugin doesn't provide syntax coloring for Dockerfiles. IDEA has own 'Docker' plugin for that.
