### ISSUE TITLE
Compatibility with PyCharm 2020.1

### ISSUE THREAD

**Issue by washeck** [adelf/idea-php-dotenv-plugin#49]
I have PyCharm 2020.1 EAP (Professional Edition), Build #PY-201.4865.17, built on February 5, 2020 and on IDE start I get the following error:

Plugin Error: The .env files support (id=ru.adelf.idea.dotenv, path=~/.local/share/JetBrains/PyCharm2020.1/idea-php-dotenv-plugin-2019.3.jar, version=2019.3) plugin is incompatible (target build range is 192 to 193.*).

**Comment by adelf** [comment]
Hi, @washeck .
I released 2020.1 today. Everything should be ok. Also, it will be good if you will check that plugin can be updated without reloading the IDE. The new 2020.1 feature.

**Comment by washeck** [comment]
@adelf Thanks, the new version fixes it. The update cannot be installed without restart of IDE. Maybe because it says that previous version is not compatible
