### ISSUE TITLE
Add support for .env.dist files

### ISSUE THREAD

**Issue by Haehnchen** [adelf/idea-php-dotenv-plugin#5]
Also support `.env.dist` for ENV variables. eg see https://github.com/symfony/flex/blob/master/src/Flex.php#L177

**Comment by adelf** [comment]
As I see all these kind of files usually copied to .env (Laravel has .env.example file). And usually both of this file with similar content are in project. This makes Go to declaration feature unconvenient - user should every time choose between .env and .env.dist file declaration. I'll try to avoid these issues in future.. maybe. But currently I'll support only .env files.

**Comment by kAlvaro** [comment]
Other files (.env-development, .env-production...) should probably only taken into account in other features (see #2).

**Comment by adelf** [comment]
![image](https://user-images.githubusercontent.com/2818394/28788596-242eaa06-762a-11e7-81f0-05e521499e8c.png)
Actually, you can add any files to .env File type. And everything will work.

![image](https://user-images.githubusercontent.com/2818394/28788636-5df6bf80-762a-11e7-99e6-76a67f24942d.png)
But after that any Go to declaration call will be with annoying choice...

**Comment by adelf** [comment]
I added .env.* files support. But they will work only if there is no main .env file in the project. Or, for example current key, which user wants to Go To Declaration, exists only in .env.dist files, when plugin redirects user to declaration in .env.dist file.

**Comment by jezmck** [comment]
Yep, we have `.env.local`, `.env.production` etc, so we need the wildcard option to work.

**Comment by adelf** [comment]
@jezmck it has. .env.* by default. and it can be configured in File types setting.
Implemented in 0.7.

**Comment by jezmck** [comment]
It seems that having both stops the wildcard working.
