### ISSUE TITLE
Override .env.$env support

### ISSUE THREAD

**Issue by siguycmo** [adelf/idea-php-dotenv-plugin#52]
Currently only `.env` files seem to have syntax highlighting, could/should this also apply to override files following the format of `.env.*` as per the [Symfony Dotenv Component](https://symfony.com/doc/current/components/dotenv.html) (using PHPStorm)?

**Comment by adelf** [comment]
Hi. Please check #34

**Comment by siguycmo** [comment]
I have checked that, I have the file types as:
![image](https://user-images.githubusercontent.com/50174207/78250966-891f8380-74e8-11ea-9aac-79710544b8f5.png)
Not sure what the actual solution is from that other ticket though?

**Comment by adelf** [comment]
I have the same config and my PhpStorm processes these files `.env.$env` or `.env.$env.local` correctly. Seems, some time ago you opened this file and marked it as text.. or ini... Check this file types and remove these patterns from there...

**Comment by siguycmo** [comment]
Hi, thanks. My filename was `.env.site.prod` looks like it doesnt support that format so have changed it to `.env.site-prod` and that works. Thanks!

**Comment by cornwe19** [comment]
FYI this issue appears to be affecting IntelliJ for some reason.

![2020-12-14_17-12-14](https://user-images.githubusercontent.com/492618/102141905-90e14700-3e2f-11eb-9f5d-1a1a84bf846f.png)
