### ISSUE TITLE
Inspection that warns the user when using spaces without surrounding quotes

### ISSUE THREAD

**Issue by nicolus** [adelf/idea-php-dotenv-plugin#54]
When using vlucas/phpdotenv, you can't use a value with spaces in it without surrounding the value with double quotes (I don't know about other .env implementations). It throws an error that says

> Dotenv values containing spaces must be surrounded by quotes

It would be really useful if this plugin could add an inspection (like the "duplicate keys" one) that warns you if you're trying to do that.

**Comment by adelf** [comment]
Inspection + quick fix added in 2020.2 version. Thanks.
