### ISSUE TITLE
Thoughts on supporting .envrc files that include export prefix

### ISSUE THREAD

**Issue by jlorenzen** [adelf/idea-php-dotenv-plugin#55]
I see this plugin supports .env files, but what are your thoughts on also supporting [direnv](https://direnv.net/) .envrc files where the variables include the `export` prefix.

**Comment by adelf** [comment]
Hi, James. dot-env plugin support `export` prefix. So, you can try just assotiate .envrc extension with .env File type:
![](https://user-images.githubusercontent.com/2818394/62718724-0ef93680-ba0f-11e9-828d-d68e3dfb3c03.png)

**Comment by jlorenzen** [comment]
@adelf Ok I tried that but it didn't seem to work. Here are some screenshots. My `.envrc` file has things like
```
export DATABASE_HOST=localhost
```
![Screen Shot 2020-05-19 at 5 30 48 PM](https://user-images.githubusercontent.com/107843/82384907-80cacb80-99f6-11ea-8da6-47ef45862732.png)

![Screen Shot 2020-05-19 at 5 29 24 PM](https://user-images.githubusercontent.com/107843/82384852-67298400-99f6-11ea-9736-df3f7cf561d9.png)

**Comment by adelf** [comment]
This plugin only highlights the .env files and auto-completes them in the code. https://plugins.jetbrains.com/plugin/7861-envfile - this plugin allows to use them in run configurations.

**Comment by jlorenzen** [comment]
@adelf ![](https://media.giphy.com/media/QLXPK5HFpzCjS/giphy.gif)
