### ISSUE TITLE
[Idea] Make autocompletion case-insensitive

### ISSUE THREAD

**Issue by sergiy-petrov** [adelf/idea-php-dotenv-plugin#56]
Currently autocompletion for .env variable is case-sensitive. I'd suggest to change this behaviour and make it case-insensitive. Please, find screenshots attached.

![image](https://user-images.githubusercontent.com/8986207/82738314-6585f600-9d3f-11ea-828c-d8027661ddd3.png)

![image](https://user-images.githubusercontent.com/8986207/82738317-6880e680-9d3f-11ea-9310-716992abe71e.png)

**Comment by adelf** [comment]
Implemented in 2020.2. Thanks.
