### ISSUE TITLE
Syntax highlighting for quoted values ending with backslash(es)

### ISSUE THREAD

**Issue by mgrinspan** [adelf/idea-php-dotenv-plugin#59]
If a variable's value is quoted but it ends with a backslash, the syntax highlighting gets thrown off.

![image](https://user-images.githubusercontent.com/8433459/85454932-6ba00a00-b56b-11ea-93d8-466e8ac6b452.png)

**Comment by adelf** [comment]
Thanks.

**Comment by adelf** [comment]
Fixed in 2020.3
