### ISSUE TITLE
Comment Support - Feature Request

### ISSUE THREAD

**Issue by KerryJones** [adelf/idea-php-dotenv-plugin#6]
PHPStorm doesn't currently understand how to comment in .env, `#`. It would be great to use Ctrl+/ to comment

**Comment by natebrunette** [comment]
@KerryJones I created a custom filetype for .env files and set the line comment to `#`. Seems to work for now.

**Comment by kAlvaro** [comment]
@natebrunette Doesn't that effectively prevent the dotenv plugin from working?

**Comment by natebrunette** [comment]
@kAlvaro Ha, I suppose it would. I guess I never used the plugin for autocompletion, I was just looking for a way to quickly comment/uncomment .env files.

**Comment by biggator** [comment]
That sounds great, adelf. Any chance you can release that soon?

**Comment by adelf** [comment]
@biggator I don't want to release only commenting.... I'll try to add some other features and release soon

**Comment by adelf** [comment]
Implemented on 0.5

**Comment by biggator** [comment]
Thanks, @adelf. The release works well.
