### ISSUE TITLE
Plugin "Lombok" is incompatible (until build 201.SNAPSHOT < IC-202.6397.94).

### ISSUE THREAD

**Issue by inthink** [adelf/idea-php-dotenv-plugin#60]
Plugin "Lombok" is incompatible (until build 201.SNAPSHOT < IC-202.6397.94).

IntelliJ IDEA 2020.2 (Community Edition)
Build #IC-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 3683M
Cores: 8
Registry: ide.tree.collapse.recursively=false
Non-Bundled Plugins: CMD Support, String Manipulation, com.intellij.ideolog, com.dubreuia, io.github.qeesung.component.HighlightBracketPair, net.vektah.codeglance, ru.adelf.idea.dotenv, AliP3CPlugin, MavenRunHelper, zielu.gittoolbox, com.ccnode.codegenerator.MyBatisCodeHelperPro, izhangzhihao.rainbow.brackets

**Comment by adelf** [comment]
It's a Lombok plugin issue. .env files support plugin just installed there...
