### ISSUE TITLE
Symfony's .env.local.php is also parsed as .env syntax

### ISSUE THREAD

**Issue by 7ochem** [adelf/idea-php-dotenv-plugin#63]
In Symfony it is possible to have a `.env.local.php` file to override other .env files and to leverage PHP's opcache.

Now this file is also parsed and highlighted as .env syntax instead of PHP syntax. It would be great if it could be excluded. And it would be awesome if the plugin would not consider the file to be .env syntax (but PHP), but if it would register the defined variables and values (e.g. for usage search and key checking).

**Comment by adelf** [comment]
I'll try to fix that. There is a workaround: add this file name as PHP file type pattern:

![image](https://user-images.githubusercontent.com/2818394/100521102-abba8700-31b2-11eb-9750-837060916f49.png)

**Comment by 7ochem** [comment]
> There is a workaround: add this file name as PHP file type pattern:

The workaround works! Thanks for that :+1:
