### ISSUE TITLE
[Suggestion] Support for dotenv-java & dotenv-kotlin

### ISSUE THREAD

**Issue by linux-china** [adelf/idea-php-dotenv-plugin#64]
https://github.com/cdimascio/dotenv-java and https://github.com/cdimascio/dotenv-kotlin 

Both share  the interface  `io.github.cdimascio.dotenv` , and  methods are `String get(String key);` and ` String get(String key, String defaultValue);` 

Thanks.

**Comment by adelf** [comment]
2021.2 version contains Java and Kotlin support.
