### ISSUE TITLE
Append backslash for long string produces error (not warning).

### ISSUE THREAD

**Issue by arafatx** [adelf/idea-php-dotenv-plugin#68]
Declare a long string and append new line with backslash `\`:

```
#file.env

hello="This is only \
one line string \
with space and might be long"

```

```
#!/bin/bash

source file.env
echo "${hello}"

```
This will produce an error regarding to the backslash :

`DotEnvTokenType.COMMENT, DotEnvTokenType.CRLF, DotEnvTokenType.EXPORT, DotEnvTokenType.KEY_CHARS or DotEnvTokenType.QUOTE expected, got '\'`

but ENV source file has no problem. Output still working:

`This is only one line string with space and might be long`

**Comment by adelf** [comment]
I'll fix it. Thank you.

**Comment by adelf** [comment]
2021.2 is released
