### ISSUE TITLE
Should allow declaring an array in ENV file

### ISSUE THREAD

**Issue by arafatx** [adelf/idea-php-dotenv-plugin#69]
Declaring an array using this form:

    array=("test1" "test2" "test3")

Will produce a warning, with the following text:

    Space inside allowed only for quoted values

Expected output: 

Shouldn't have this warning because it's a valid array and sourcing the file containing this form of array has no issue.

Thanks.

**Comment by adelf** [comment]
What library supports arrays?

**Comment by arafatx** [comment]
I think I have overused this ENV with bash sourcing and thinking it should support an array. ENV file shouldn't have array complexity. Please ignore this request.
