### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by xyxz-web** [adelf/idea-php-dotenv-plugin#70]
I'd like to use this plugin as it looks very useful, but in order to get it approved I need information on how it handles privacy.
Does it collect any personal information?
If so, what kind of data is collected and when is it collected?
Would also be great if you could add this to the documentation.

Thank you very much!

**Comment by adelf** [comment]
Plugin collects all environment variables and their values from project files during indexing and stores it in the internal IntelliJ IDE storages in your local hard drive. Nowhere else.
However, I think I can add the option to don't store values... I'll ask JetBrains guys about it. Thank you.

**Comment by adelf** [comment]
Starting from 2021.2 version values storing is configurable:

![image](https://user-images.githubusercontent.com/2818394/120878586-2df29080-c5c6-11eb-9344-70ad587f5b1e.png)
