### ISSUE TITLE
Support all .env* files

### ISSUE THREAD

**Issue by lk77** [adelf/idea-php-dotenv-plugin#72]
Hello,

it would be great to support all .env files, like .env.testing/.env.local/.env.dusk.local etc...

i think all files starting with .env should be supported.

thanks.

**Comment by adelf** [comment]
Hi, Mathias. Actually, I declare 3 patterns for .env files by default:

```
.env
*.env
.env.*
```

The last one should work for you.

**Comment by lk77** [comment]
Well that's strange, only .env seems to be working, i can mark it as plain text or as .env files,
but i don't have the option for the others .env files.

**Comment by adelf** [comment]
Exactly. The Javascript plugin made a mistake in 2020.1 and replaced my mapping for .env files. They fixed it immediately.. but maybe your version is still wrong.

**Comment by lk77** [comment]
ok, i will update my version then, thanks.

**Comment by dahei** [comment]
I have the same issue with latest PHPStorm 2021.1.1 - `env.local` and similar names files have no syntax highlighting. I can see the the filetype patterns, but `.env.*` doesn't seem to match.

Any idea where to fix this?

**Comment by lk77** [comment]
Hello,

i'm now fully updated and it works for me on 2021.1.2

**Comment by dahei** [comment]
Can't confirm. I am on the same PHPStorm Version and build.

Plugin version: 
![image](https://user-images.githubusercontent.com/2070820/120299402-42374480-c2cb-11eb-98d9-5687544ba263.png)

`.env.local` still has no syntax highlighting.

**Comment by adelf** [comment]
@dahei what file type do you see for .env.local file(it should be shown in the right bottom corner of editor)? Text? Or?

Then, please, check Editor - File types in the Settings and find this file type. I’m sure the problem is there. “.env.*” pattern usually works if there is no any overriding.

**Comment by dahei** [comment]
Here are my settings and 2 example files: 

![image](https://user-images.githubusercontent.com/2070820/120303585-449b9d80-c2cf-11eb-96f0-b713ae8a8177.png)

![image](https://user-images.githubusercontent.com/2070820/120303662-58df9a80-c2cf-11eb-97aa-544d15e2ef00.png)

**Comment by adelf** [comment]
@dahei could you check Text file type?

**Comment by dahei** [comment]
That's it!! - `.env.local` was explicitly set there 🤦 . I guess it happened before I installed your plugin (PHPStorm asking for file type as it couldn't know what it was). Sorry for the confusion! All fine!

**Comment by lk77** [comment]
yeah, you should right click on the file and choose "Mark as '.env file'"
