### ISSUE TITLE
Idea 2021.2 EAP support

### ISSUE THREAD

**Issue by EugeneDraitsev** [adelf/idea-php-dotenv-plugin#76]
Hi,

Would be awesome to update plugin for latest EAP version

Thank you for the great plugin!

**Comment by adelf** [comment]
Hi, Eugene. I’ll try to release it tomorrow.

**Comment by adelf** [comment]
2021.2 is released

**Comment by gt-novelt** [comment]
@adelf unfortunately I had to rollback PyCharm to 2021.1 because this great plugin wasn't working for me.

Maybe it has something to do with the fact that my project and interpreter are located in WSL ? I was not seeing the EnvFile panel 😕. 

Let me know if I can help debugging

**Comment by adelf** [comment]
@gt-novelt you probably mean this plugin: https://github.com/ashald/EnvFile/

**Comment by gt-novelt** [comment]
> @gt-novelt you probably mean this plugin: https://github.com/ashald/EnvFile/

haha yes 👍 

Now I am confused, I got here from this link:
![image](https://user-images.githubusercontent.com/37072369/122289103-9d378100-cef2-11eb-998c-ab331de3910e.png)

**Comment by adelf** [comment]
"EnvFile panel" is a part of EnvFile plugin. 
.env files support - just makes some syntax coloring for .env files and completion for os.environ.get calls

**Comment by gt-novelt** [comment]
Oh right!

Sorry 😅
