### ISSUE TITLE
[Feature request] Gradle run configurations support

### ISSUE THREAD

**Issue by fehbari** [adelf/idea-php-dotenv-plugin#79]
Hi. In light of the [EnvFile](https://github.com/ashald/EnvFile/issues/140) plugin no longer working on 2021.2, IntelliJ suggested I installed your plugin instead.

Unfortunately, it doesn't seem to work with Gradle run configurations. With EnvFile, I was able to check Gradle support in the UI, and all tasks (e.g. `run`, `test`, etc) would have variables from the .env file loaded correctly and available to the application.

Would it be possible to add Gradle support to this plugin? If the info is useful at all, EnvFile seems to support it with the following provider [GradleEnvFileProvider](https://github.com/ashald/EnvFile/blob/develop/modules/products/idea/src/main/java/net/ashald/envfile/products/idea/GradleEnvFileProvider.java)

**Comment by adelf** [comment]
As I see, you've managed to make it work. My plugin makes syntax coloring and completions for .env values. Maybe in the future, our plugins will be merged into one...

**Comment by fehbari** [comment]
@adelf I see, I misinterpreted what your plugin is supposed to do. I was under the impression it also handled injection of the variables into processes like EnvFile does. My apologies.

I do appreciate the syntax highlighting and completion feature though, so I'll keep both (: Thank you.
