### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by cn-core** [adelf/idea-php-dotenv-plugin#81]
![image](https://user-images.githubusercontent.com/30290251/127276022-c15c0a42-0f79-4119-85e8-8661e2da3e1d.png)

File 'D:\xxx\JetBrains\Toolbox\apps\IDEA-U\ch-0\212.4746.92.plugins\EnvFile\lib\envfile-3.2.1.jar' contains invalid plugin descriptor

**Comment by adelf** [comment]
It’s another plugin - https://plugins.jetbrains.com/plugin/7861-envfile

**Comment by cn-core** [comment]
@adelf thank you !

**Comment by cn-core** [comment]
@adelf thank you !
