### ISSUE TITLE
Plugin not working on Pycharm 2021.2.

### ISSUE THREAD

**Issue by mauricio-repetto** [adelf/idea-php-dotenv-plugin#88]
Hi I upgraded recently the pycharm version and now the env plugin is not working anymore. Here are the pycharm version details:

![image](https://user-images.githubusercontent.com/11300196/128055569-8887a540-1799-44f3-8ada-ddb619e6f39e.png)

And the plugin is installed and enabled:

![image](https://user-images.githubusercontent.com/11300196/128055686-cb948651-7ccf-4e1f-a08e-02d630028c88.png)

But when you go to the configuration of a script to run en env tab is not being displayed anymore:

![image](https://user-images.githubusercontent.com/11300196/128055864-97827f7a-1705-4357-bdd5-b033d9fc9634.png)

I've tried disabling it and enabling it again (same with uninstall/install).. nothing worked :/

**Comment by adelf** [comment]
Env tab is a feature of the "EnvFile" plugin - https://plugins.jetbrains.com/plugin/7861-envfile
