### ISSUE TITLE
It does not seem it is working with 2021.2

### ISSUE THREAD

**Issue by melastmohican** [adelf/idea-php-dotenv-plugin#89]
And I cannot install the previous one because is marked as incompatible

**Comment by adelf** [comment]
What is doesn’t work? If you’re about Env tab - it’s not a part of this plugin.

**Comment by melastmohican** [comment]
There is no UI for the plugin visible, how can I select .env to use if it is not there. It used to be a tab before.
![RunDebug](https://user-images.githubusercontent.com/240840/128101965-99c14d12-83f2-4b75-8b34-d936c2b45725.PNG)

**Comment by adelf** [comment]
Env tab is a feature of the "EnvFile" plugin - https://plugins.jetbrains.com/plugin/7861-envfile
