### ISSUE TITLE
[Bug]: version '2021.3.0.212' is not compatible with ... PS-213.3714.448

### ISSUE THREAD

**Issue by pgnd** [adelf/idea-php-dotenv-plugin#93]
### Bug description

launch latest PhpStorm snap update,

plugin error:

"Plugin '.env files support' (version '2021.3.0.212') is not compatible with the current version of the IDE, because it requires build 212.* or older but the current build is PS-213.3714.448"

### Plugin version

4.4.0.212

### Operating system

Linux

**Comment by Baneeishaque** [comment]
Same here....

**Comment by adelf** [comment]
The update will be approved by JetBrains soon. If you want it earlier, you can download it manually here:
https://plugins.jetbrains.com/plugin/9525--env-files-support/versions/stable/138435

**Comment by Baneeishaque** [comment]
> The update will be approved by JetBrains soon. If you want it earlier, you can download it manually here: https://plugins.jetbrains.com/plugin/9525--env-files-support/versions/stable/138435

Working as expected... @adelf
