### ISSUE TITLE
Doesn't work with IDEA (2021.2.3)

### ISSUE THREAD

**Issue by 10D24D** [adelf/idea-php-dotenv-plugin#99]
Hello, recently I found that the plugin does not support the latest version of IDEA (2021.2.3), either using shortcut notes or text highlighting. Please see how to solve this problem.

**Comment by marcelhillesheim** [comment]
Works for me (Intellij 2021.2.3).

Did you try this?
https://github.com/adelf/idea-php-dotenv-plugin/issues/90#issuecomment-898388301

**Comment by 10D24D** [comment]
> 

Thanks. I tried, but it didn't work.

---

Here's my environment information

IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Licensed to IntelliJ IDEA Evaluator
Expiration date: December 20, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2034M
Cores: 8
Non-Bundled Plugins: org.jetbrains.plugins.vue (212.5457.27), org.jetbrains.kotlin (212-1.6.0-release-799-IJ5457.46), ru.adelf.idea.dotenv (2021.3.0.212)
Kotlin: 212-1.6.0-release-799-IJ5457.46

**Comment by feedmypixel** [comment]
Making sure the **.env file** is setup correctly in File Types worked for me as described https://github.com/adelf/idea-php-dotenv-plugin/issues/90#issuecomment-898388301

I had two entries in `Recognised File Types`:
- `.env`
- `.env file`

Moving the `File name patterns`:
- `.env`
- `*.env` 
- `.env.*` 

To the **.env file** definition and deleting the `.env` definition worked for me and has given me text highlighting and shortcut notes on Cmd ⌘ + hover on environment variables


```
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
******
******
Runtime version: 11.0.12+7-b1504.40 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Registry: debugger.watches.in.variables=false, js.debugger.webconsole=false, eslint.additional.file.extensions=svelte
Non-Bundled Plugins: mobi.hsz.idea.gitignore (4.3.0), org.intellij.plugins.hcl (0.7.14), AWSCloudFormation (212.4746.57), org.intellij.plugins.postcss (212.5457.18), nl.bryanderidder.regexrenamefiles (1.1.5), com.jinsihou.react.snippets (1.1.0), net.ashald.envfile (3.2.2), com.suming.react.PropTypes (1.1.5), intellij.prettierJS (212.5080.8), ru.adelf.idea.dotenv (2021.3.0.212)
Kotlin: 212-1.5.10-release-IJ5457.46
```

**Comment by IlFalco1992** [comment]
![image](https://user-images.githubusercontent.com/25423312/146209698-6bc3d94a-deb5-4b65-8005-93edf2d3bb45.png)
Doesn't work on PHPStorm 2021.3

**Comment by adelf** [comment]
@IlFalco1992 there is a version for 2021.3: https://plugins.jetbrains.com/plugin/9525--env-files-support/versions/stable/138435

Restart IDE button probably means that IDE already uploaded a new version and wants to restart

**Comment by IlFalco1992** [comment]
@adelf whoops... Well, thanks a lot, it worked
